import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'

import Nav from '@/components/navbar'

const montserrat = Montserrat({ weight: '400', subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={montserrat.className}>{children}</body>
    </html>
  )
}

// background color for light mode and dark mode? #ffffff - white background
